# Generated by Django 4.1.3 on 2023-03-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default='', max_length=50, unique=True)),
                ('emp_name', models.CharField(default='', max_length=70)),
                ('emp_address', models.CharField(default='', max_length=150)),
                ('emp_email', models.CharField(default='', max_length=100)),
                ('emp_phone', models.CharField(default='', max_length=30)),
                ('emp_dep', models.CharField(default='', max_length=100)),
                ('emp_pass', models.CharField(default='', max_length=100)),
                ('emp_photo', models.ImageField(default='', upload_to='image/employee')),
            ],
        ),
        migrations.CreateModel(
            name='Hradmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default='', max_length=50, unique=True)),
                ('emp_name', models.CharField(default='', max_length=100)),
                ('emp_pass', models.CharField(default='', max_length=200)),
                ('super_hr', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_id', models.CharField(default='', max_length=50, unique=True)),
                ('emp_id', models.CharField(default='', max_length=50)),
                ('emp_name', models.CharField(default='', max_length=70)),
                ('emp_dep', models.CharField(default='', max_length=100)),
                ('s_date', models.DateField(default='')),
                ('e_date', models.DateField(default='')),
                ('l_day', models.IntegerField(default='')),
                ('l_type', models.CharField(default='', max_length=50)),
                ('l_status', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
