# Generated by Django 4.1.3 on 2023-03-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default='', max_length=50)),
                ('attendace_timing', models.DateField(blank=True, default='', null=True)),
                ('attendance_date', models.DateTimeField(blank=True, default='', null=True)),
            ],
        ),
    ]
