# Generated by Django 4.1.3 on 2023-03-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0002_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendace_timing',
            new_name='attendace_date',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance_date',
            new_name='attendance_time',
        ),
    ]
