# Generated by Django 4.1.7 on 2023-03-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0003_rename_attendace_timing_attendance_attendace_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_time',
            field=models.TimeField(blank=True, default='', null=True),
        ),
    ]
