# Generated by Django 4.1.7 on 2023-04-04 11:20

import HRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0004_alter_attendance_attendance_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hradmin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendace_date',
            field=models.DateField(blank=True, default=HRM.models.Attendance.date, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_time',
            field=models.TimeField(blank=True, default=HRM.models.Attendance.time, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='emp_id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_photo',
            field=models.ImageField(default='', upload_to=HRM.models.namechange),
        ),
        migrations.AlterField(
            model_name='hradmin',
            name='emp_id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
