# Generated by Django 4.1.7 on 2023-04-10 19:00

import HRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0005_remove_attendance_id_remove_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAndAttendanceCount',
            fields=[
                ('emp_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('meadical_leave', models.IntegerField(blank=True, default='', null=True)),
                ('Personal_leave', models.IntegerField(blank=True, default='', null=True)),
                ('attendance_count', models.IntegerField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_pass',
            field=models.CharField(default=HRM.models.Employee.password, max_length=100),
        ),
    ]
