# Generated by Django 4.1.7 on 2023-04-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0006_leaveandattendancecount_alter_employee_emp_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveandattendancecount',
            name='Personal_leave',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='leaveandattendancecount',
            name='attendance_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leaveandattendancecount',
            name='meadical_leave',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
    ]
