# Generated by Django 4.1.7 on 2023-04-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0009_rename_meadical_leave_leaveandattendancecount_medical_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='emp_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
