# Generated by Django 4.1.7 on 2023-04-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0010_attendance_emp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveandattendancecount',
            name='attendance_count',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
