# Generated by Django 4.1.7 on 2023-05-12 12:25

import HRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0011_remove_leaveandattendancecount_attendance_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_pass',
            field=models.CharField(default=HRM.models.Employee.password, max_length=500),
        ),
    ]
