# Generated by Django 4.1.7 on 2023-05-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0012_alter_employee_emp_pass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveAndAttendanceCount',
            new_name='LeaveCount',
        ),
    ]
